In [ ]:
from duckdb import connect
from data.ingest.portwatch.run import table_name, connection
con = connection()
df = con.execute(
    "SELECT * " \
    f"FROM {table_name}").fetchdf()

CatalogException: Catalog Error: Table with name portwatch does not exist!
Did you mean "pg_attrdef"?

LINE 1: SELECT * FROM portwatch
                      ^

In [ ]:
con.

In [ ]:
con.execute("SELECT * FROM lake.snapshots();").fetch_df()

,snapshot_id,snapshot_time,schema_version,changes,author,commit_message,commit_extra_info
0,0,2026-04-03 18:28:55.480580+02:00,0,{'schemas_created': ['main']},None,None,None
1,1,2026-04-03 18:28:55.541765+02:00,1,"{'tables_created': ['main.weather'], 'tables_i...",None,None,None

In [1]:
import duckdb
con = duckdb.connect()
con.execute("ATTACH 'ducklake:sqlite:data/metadata/metadata.sqlite' AS lake (DATA_PATH 'data/parquet/')")
con.execute("USE lake")

In [6]:
con.execute(
    # "CREATE TABLE people (id INTEGER, name VARCHAR, salary FLOAT);"
    "INSERT INTO people VALUES (3, 'John', 92_000.0), (4, 'Anna', 100_000.0);"
    )

In [ ]:
con.execute("""
                MERGE INTO people
                USING (
                    SELECT
                        unnest([3, 1]) AS id,
                        unnest(['Sarah', 'John']) AS name,
                        unnest([95_000.0, 105_000.0]) AS salary
                ) AS upserts
                ON (upserts.id = people.id)
                WHEN MATCHED THEN UPDATE
                WHEN NOT MATCHED THEN INSERT;

            FROM people;""")

In [7]:
con.execute("SELECT * FROM lake.snapshots();").fetchdf()

,snapshot_id,snapshot_time,schema_version,changes,author,commit_message,commit_extra_info
0,0,2026-05-24 18:08:26.669465+02:00,0,{'schemas_created': ['main']},None,None,None
1,1,2026-05-24 18:08:29.581624+02:00,1,{'tables_created': ['main.people']},None,None,None
2,2,2026-05-24 18:08:29.593098+02:00,1,{'inlined_insert': ['1']},None,None,None
3,3,2026-05-24 18:08:31.921421+02:00,1,"{'tables_inserted_into': ['1'], 'inlined_delet...",None,None,None
4,4,2026-05-24 18:09:28.013817+02:00,1,{'inlined_insert': ['1']},None,None,None
5,5,2026-05-24 18:09:58.976277+02:00,1,{'inlined_insert': ['1']},None,None,None

In [8]:
con.execute("SELECT * FROM people;").fetchdf()

   id   name    salary
0   1   John  105000.0
1   3  Sarah   95000.0
2   2   Anna  100000.0
3   3   John   92000.0
4   4   Anna  100000.0
5   3   John   92000.0
6   4   Anna  100000.0